### PR TITLE
Create new user with encrypted password

### LINKED ISSUE #8: Create new user with encrypted password

### PR DESCRIPTION
**Pull request by Vimbayinashe**
This pull requests creates an endpoint that create a new user which is saved in the database with an encrypted password.

Closes #8

### CODE REVIEW

**Comment by Vimbayinashe** [comment]
I have marked this pull request as a draft because I am currently unable to connect to the server when it is running as a container.
 
It is however possible to connect to the server and create a new user when the server is running in Intellij.

**Comment by Vimbayinashe** [comment]
Settings for Consul host i docker-compose will be replaced with the entire project's consul service once that is ready.

**Comment by Vimbayinashe** [comment]
Creating a new user automatically assigns default role "ROLE_USER" now. 
Example JSON body:
```
{
   "email": "user@mymail.com",
   "password": "tuesday"
}
```

**Review by Philippevial — APPROVED** [review]
Working as intended!

**Pull request merged**
